package com.example.demo2.componentmodel;

import java.util.Objects;

/**
 * Component -> abstract class -> 5 Private variables -> interface for component models : ex Battery, switch, lightbulb, etc
 */
public abstract class Component {
    // Private variables
    private final int COMPONENT_ID;
    private double componentX;
    private double componentY;
    private final String COMPONENT_TYPE;
    public static double zoomScale;

    // Component Constructor method
    public Component(double x, double y, String type) {
        //TODO: Replace with ID generated by database using auto-increment
        COMPONENT_ID = (int)(Math.random() * 7000) + 1;
        COMPONENT_TYPE = type;
        componentX = x;
        componentY = y;
    }

    // Getter Methods
    public String getComponentType() {
        return COMPONENT_TYPE;
    }
    public double getComponentX() {
        return componentX;
    }
    public double getComponentY() {
        return componentY;
    }

    // Setter Methods
    public void setComponentX(double x) {
        componentX = x;
    }
    public void setComponentY(double y) {
        componentY = y;
    }
    public int getComponentID() {
        return COMPONENT_ID;
    }

    // equals method -> returns boolean
    @Override
    public boolean equals(Object o) {
        if (o instanceof Component) {
            return COMPONENT_ID == ((Component) o).getComponentID() && COMPONENT_TYPE.equals(((Component) o).getComponentType());
        }
        else {
            return false;
        }
    } // End equals method

    // hashCode method -> returns int
    @Override
    public int hashCode() {
        return Objects.hash(COMPONENT_ID, COMPONENT_TYPE);
    }

} // End Component abstract class
