package com.example.demo2.componentmodel;

import java.util.Objects;

public abstract class Component {
    private int COMPONENT_ID = -1;
    private double componentX;
    private double componentY;
    private final String COMPONENT_TYPE;
    public static double zoomScale;

    public Component(double x, double y, String type) {
        //TODO: Replace with ID generated by database using auto-increment
        COMPONENT_TYPE = type;
        componentX = x;
        componentY = y;
    }

    public String getComponentType() {
        return COMPONENT_TYPE;
    }

    public double getComponentX() {
        return componentX;
    }

    public double getComponentY() {
        return componentY;
    }

    public void setComponentX(double x) {
        componentX = x;
    }

    public void setComponentY(double y) {
        componentY = y;
    }

    public void setComponentID(int id) {
        COMPONENT_ID = id;
    }
    public int getComponentID() {
        return COMPONENT_ID;
    }
    public boolean hasValidID() {
        return COMPONENT_ID > 0;
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof Component) {
            Component other = (Component) o;
            return COMPONENT_ID == ((Component) o).getComponentID() && COMPONENT_TYPE.equals(((Component) o).getComponentType());
        }
        else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(COMPONENT_ID, COMPONENT_TYPE);
    }
}
